### ISSUE TITLE
Threading and calling Xam.Plugin.Mixpanel.iOS

### ISSUE THREAD

**Issue by Lelelo1** [beeradmoore/Xam.Plugin.Mixpanel.iOS#5]
I wanted to ask to if there can be misbehaviour when threading. Do you know if all calls to `Xam.Plugin.Mixpanel.iOS.Mixpanel` should be preformed on the main thread - or does it now matter?
There is no problem that I have run into currently, in development. In production it can be hard to discover.

**Comment by beeradmoore** [comment]
In any of my projects I have not thought of this or handled it in any special way, nor  have I come across any issues. 

This is more of a question for the [Mixpanel iPhone repo](https://github.com/mixpanel/mixpanel-iphone/), as the `Xam.Plugin.Mixpanel.iOS` project is a binding for their library. We are quite a few versions behind (us 3.6.2, them 3.9) due to changes in xcode we were not able to update this library.

If you look through the official releases though you will see things like in v3.7.1 "making timedEvents threadsafe".
